### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::8124

### ISSUE THREAD

**Issue by metapodcod** [mhanberg/jekyll-postcss#35]
```
ruby/3.0.0/gems/jekyll-postcss-0.5.0/bin/postcss:31
      throw err;
      ^

Error: listen EADDRINUSE: address already in use :::8124
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.startServer (/home/metapodcod/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/bin/postcss:34:12)
    at Object.<anonymous> (/home/metapodcod/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/bin/postcss:42:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8124
}
                    done in 1.044 seconds.
```

**Comment by benoliver999** [comment]
I had this issue, but now I can't reproduce it. However, it turned into:

```

PostCSS Server listening on port 8124...
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:70:in `rescue in start_dev_server': Could not connect to the PostCSS server (RuntimeError)
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:61:in `start_dev_server'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:13:in `initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `new'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `block in initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `fetch'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `new'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `block (2 levels) in instantiate_subclasses'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `map!'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `block in instantiate_subclasses'
	from <internal:kernel>:90:in `tap'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:319:in `instantiate_subclasses'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:133:in `setup'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:36:in `initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /home/ben/.gem/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/ben/.gem/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:477:in `exec'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
	from /home/ben/.gem/ruby/3.0.0/bin/bundle:23:in `load'
	from /home/ben/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
/home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:62:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:62:in `open'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:62:in `start_dev_server'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll-postcss/socket.rb:13:in `initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `new'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `block in initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `fetch'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-postcss-0.5.0/lib/jekyll/converters/postcss.rb:16:in `initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `new'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `block (2 levels) in instantiate_subclasses'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `map!'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:321:in `block in instantiate_subclasses'
	from <internal:kernel>:90:in `tap'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:319:in `instantiate_subclasses'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:133:in `setup'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:36:in `initialize'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `new'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:30:in `process'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/ben/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/ben/.gem/ruby/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /home/ben/.gem/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/ben/.gem/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:477:in `exec'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
	from /home/ben/.gem/ruby/3.0.0/bin/bundle:23:in `load'
	from /home/ben/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
```

I managed to fix (?) it by adding `require 'resolv-replace'` to `lib/jekyll-postcss.rb`

**Comment by metapodcod** [comment]
> I managed to fix (?) it by adding `require 'resolv-replace'` to `lib/jekyll-postcss.rb`

where did you add this?

**Comment by benoliver999** [comment]
Next to the other require statements - maybe line 6?

**Comment by metapodcod** [comment]
> Next to the other require statements - maybe line 6?
> […](#)
> On 22 December 2021 00:50:28 GMT, Yusuf ***@***.***> wrote: > I managed to fix (?) it by adding `require 'resolv-replace'` to `lib/jekyll-postcss.rb` where did you add this? -- Reply to this email directly or view it on GitHub: [#35 (comment)](https://github.com/mhanberg/jekyll-postcss/issues/35#issuecomment-999195962) You are receiving this because you commented. Message ID: ***@***.***>

sorry dude i really don't understand anything. English is not my native language, maybe that's why

**Comment by benoliver999** [comment]
No problem.

On my computer I opened the file called `lib/jekyll-postcss.rb`

(For me on my computer this was in `~/.gems` but I am on Linux)

Below line 5 I added a new line and wrote:

`require 'resolv-replace' to lib/jekyll-postcss.rb`

Then I saved the file.

It's not perfect because I edited the package itself, but until we can find the problem this worked for me.
